export { default as Blog } from './blog/Blog'
export { default as Features } from './features/Features'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Possibility } from './possibility/Possibility'
export { default as WhatCREAMCOLLAR } from './whatCREAMCOLLAR/WhatCREAMCOLLAR'
export { default as Opportunity } from './opportunity/Opportunity'
export {default as How} from './how/How'