import React from 'react'

import './whatCREAMCOLLAR.css';
const WhatCREAMCOLLAR = () => {
  return (
    <div className='creamcollar__whatcrm section__margin'>
      <div className='creamcollar__whatcrm-contailer-title-text-upper'>
        <h1>90%</h1>
        <h1>$0.5-1T</h1>
        <h1>90%</h1>
      </div>
      <div className='creamcollar__whatcrm-contailer-title-text-upper-para'>
        <p>of future differentiating car features are software-based</p>
        <p>software and data driven market volume in 2035</p>
        <p>of accidents can be reduced by autonomous vehicles</p>
      </div>
      <div className='creamcollar__whatcrm-contailer-title-text-lower'>
        <h1>300 mn</h1>
        <h1>25 GB</h1>
        <h1>50%</h1>
      </div>
      <div className='creamcollar__whatcrm-contailer-title-text-lower-para'>
        <p>lines of code involved for one vehicle within next few years</p>
        <p>of data generated by every connected car per hour</p>
        <p>of the vehicle cost will be of software by 2030 </p>
      </div>
    </div>
  )
}

export default WhatCREAMCOLLAR